#!/bin/bash

# Remove any previous pijuice.py in /usr/lib/python3/dist-packages
# New one is installed in /usr/lib/python3.7/dist-packages which is later in the Python path

if [ -f /usr/lib/python3/dist-packages/pijuice.py ]; then
    rm /usr/lib/python3/dist-packages/pijuice.py
fi

