/*
 * osloop.c
 *
 *  Created on: 19.03.21
 *      Author: jsteggall
 */

// ----------------------------------------------------------------------------
// Include section - add all #includes here:

#include "main.h"
#include "system_conf.h"

#include "adc.h"
#include "iodrv.h"

// ----------------------------------------------------------------------------
// Defines section - add all #defines here:

// ----------------------------------------------------------------------------
// Function prototypes for functions that only have scope in this module:

void OSLOOP_Service(void);


// ----------------------------------------------------------------------------
// Variables that only have scope in this module:

static volatile uint32_t m_osloopTimeTrack[100u];
static uint32_t m_osloopTimeTrackIdx = 0u;

// ----------------------------------------------------------------------------
// Variables that have scope from outside this module:

extern TIM_HandleTypeDef htim6;

// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// INTERRUPT HANDLERS
// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// ****************************************************************************
/*!
 * OSLOOP_TIMER_IRQHandler handles the IRQ generated by the timer. Actually, will
 * just be on update and triggers the osloop.
 */
// ****************************************************************************
void OSLOOP_TIMER_IRQHandler(void)
{
	OSLOOP_Service();

	TIMER_OSLOOP->SR &= ~(TIM_IT_UPDATE);
}


// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// FUNCTIONS WITH GLOBAL SCOPE
// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// ****************************************************************************
/*!
 * OSLOOP_Init configures the module to a known initial state
 * @param	none
 * @retval	none
 */
// ****************************************************************************
void OSLOOP_Init(void)
{
	const uint32_t sysTime = HAL_GetTick();

	ADC_Init(sysTime);
	IODRV_Init(sysTime);

	GPIO_InitTypeDef GPIO_InitStruct;

	//Configure GPIOB output pins
	GPIO_InitStruct.Pin = GPIO_PIN_14;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

	/* Start the os timer */
	TIMER_OSLOOP->CR1 |= TIM_CR1_CEN;
	TIMER_OSLOOP->DIER |= TIM_IT_UPDATE;
}


// ****************************************************************************
/*!
 * OSLOOP_Service calls the module service routines. None must block!!!
 *
 * @param	sysTime		current value of the ms tick timer
 * @retval	none
 */
// ****************************************************************************
void OSLOOP_Service(void)
{
	const uint32_t sysTime = HAL_GetTick();

	ADC_Service(sysTime);
	IODRV_Service(sysTime);

	m_osloopTimeTrack[m_osloopTimeTrackIdx] = sysTime;
	m_osloopTimeTrackIdx++;

	if (100u == m_osloopTimeTrackIdx)
	{
		m_osloopTimeTrackIdx = 0u;

		HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_14);
	}
}


// ****************************************************************************
/*!
 * OSLOOP_AtomicAccess is a really awful way of ensuring that variables are not
 * half baked on access or change if evaluated twice. Don't use this unless you
 * are desperate.
 *
 * @param	bool		true = access to a variable is required
 * 						false = access to a variable is no longer required
 * @retval	none
 */
// ****************************************************************************
void OSLOOP_AtomicAccess(bool access)
{
	if (true == access)
	{
		TIMER_OSLOOP->DIER &= ~(TIM_IT_UPDATE);
	}
	else
	{
		TIMER_OSLOOP->DIER |= TIM_IT_UPDATE;
	}
}

